DATASET:
  BACKGROUND_COLOR: 255.0
  DATA_PATH: /content/drive/MyDrive/3DRR/validation/BlueHawaii
  NAME: BlueHawaii
MODEL:
  DENSIFY_GRAD_THRESH: 0.0002
  DENSIFY_INTERVAL: 100
  DENSIFY_START_STEP: 500
  DENSIFY_STOP_STEP: 3000
  LAMBDA_SSIM: 0.2
  LOG_INTERVAL_STEP: 100
  LR_MEANS: 0.00016
  LR_MEANS_FINAL: 1.6e-06
  LR_OPACITIES: 0.05
  LR_QUATS: 0.001
  LR_SCALES: 0.005
  LR_SH0: 0.0025
  LR_SHN: 0.000125
  NAME: Simple3DGS
  NUM_INIT_POINTS: 100000
  OPACITY_RESET_INTERVAL: 3000
  SCENE_SCALE: 2.0
  SH_DEGREE: 3
  SH_UPGRADE_INTERVAL: 1000
  TRAIN_TOTAL_STEP: 5000
  VAL_INTERVAL_STEP: 1000
